version: "3"
services:
#  db:
#    image: mysql:8
#    container_name: telegrambot.db
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: admin
#      MYSQL_DATABASE: telegram_bot
#      TZ: UTC
#    volumes:
#      - db-data:/var/lib/mysql

  telegram-bot:
    image: telegram-bot:latest
    restart: always
    ports:
      - '8080:8080'
    container_name: go-telegram-bot

#volumes:
#  db-data: