version: "3"
services:
  db:
    image: mysql:8
    container_name: telegrambot.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: minhnq
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: telegramdb
      TZ: UTC
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: